### ISSUE TITLE
Cannot find module 'F:\mern-booking-app\backend\dist\index.js'

### ISSUE THREAD

**Issue by bibekrawat2020** [chrisblakely01/mern-booking-app#1]
I followed every step as you have mentioned in github. Whenever I run npm start in backend the following error occurs:
`
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'F:\mern-booking-app\backend\dist\index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
`
I am new to mern development. I need help please.

**Comment by chrisblakely01** [comment]
can you see the `dist` folder in your backend folder? it should look like this:

![Screenshot 2024-01-10 092956](https://github.com/chrisblakely01/mern-booking-app/assets/10871707/5197f127-60a8-43bb-8be8-86621ea5e19d)

if not reapply the steps to create it because it sounds like the file/folder isn't there

**Comment by bibekrawat2020** [comment]
I appreciate your help. As I went through comment section of the video, I learned that I should run "npm run build" in order to get dist folder.
